stages:
  - build
  - test
  - test_installer
  - test_hardware
  - deploy

#####################################

variables:
  GIT_SUBMODULE_STRATEGY: recursive

#####################################
# Templates

.src_tests:
    tags:
     - matlab
    stage: test
    dependencies:
     - build:v1.2.0
    artifacts:
        when: always
        name: "$CI_COMMIT_REF_NAME"
        paths:
            - test/logs/
            - Report.pdf
        reports:
            junit: test/BSPTestResults.xml

.installer_tests:
    tags:
     - vivado
     - matlab
    stage: test_installer
    dependencies:
     - build:2018_R2
    artifacts:
        when: always
        name: "$CI_COMMIT_REF_NAME"
        paths:
            - test/logs/
            - mltbx/
            - zip/
            - Report.pdf
            - test/logs/
        reports:
            junit: test/BSPTestResults.xml

#####################################

# Default build
build:v1.2.0:
    tags:
     - matlab
    stage: build
    script:
     - export MLRELEASE=R2019b
     - export TOFBRANCH=v1.2.0
     - ./CI/scripts/dockermake build
     - export INCLUDE_EXAMPLES=1
     - ./CI/scripts/dockermake gen_tlbx
     - mkdir mltbx
     - ls *.mltbx
     - cp *.mltbx mltbx/
    artifacts:
        paths:
            - mltbx/
            - deps/

build:master:
    tags:
     - matlab
    stage: build
    script:
     - export MLRELEASE=R2019b
     - export TOFBRANCH=fix-matlab-adaptor-build
     - ./CI/scripts/dockermake build
     - export INCLUDE_EXAMPLES=1
     - ./CI/scripts/dockermake gen_tlbx
     - mkdir mltbx
     - ls *.mltbx
     - cp *.mltbx mltbx/
    artifacts:
        paths:
            - mltbx/
            - deps/

#####################################

# Test HWA no install
test:v1.2.0:
    extends: .src_tests
    script:
     - export MLRELEASE=R2019b
     - ls
     - ls deps/
     - ./CI/scripts/dockermake test
